apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickandmorty-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rickandmorty-api
  template:
    metadata:
      labels:
        app: rickandmorty-api
    spec:
      containers:
        - name: rickandmorty-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
