apiVersion: v1
kind: Service
metadata:
  name: rickandmorty-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: rickandmorty-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
